language: python
python:
  - "3.3"
install:
  - pip install .
  - pip install pytest-cov coveralls
script:
  py.test --cov=githubarium
after_success:
  coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4113dbdc6199228a4bb
    on_success: change
    on_failure: always
    on_start: false
